//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceLocation
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosCore.Context", IsReference=true)]
    public partial class Location : object
    {
        
        private int LocationIdField;
        
        private string NameField;
        
        private System.Collections.Generic.List<ServiceReferencePhoto.Photo> PhotosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId
        {
            get
            {
                return this.LocationIdField;
            }
            set
            {
                this.LocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePhoto.Photo> Photos
        {
            get
            {
                return this.PhotosField;
            }
            set
            {
                this.PhotosField = value;
            }
        }
    }
    
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLocation.ILocation")]
    public interface ILocation
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetLocations", ReplyAction="http://tempuri.org/ILocation/GetLocationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferenceLocation.Location>> GetLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/AddLocation", ReplyAction="http://tempuri.org/ILocation/AddLocationResponse")]
        System.Threading.Tasks.Task AddLocationAsync(ServiceReferenceLocation.Location location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/VerifyLocationExists", ReplyAction="http://tempuri.org/ILocation/VerifyLocationExistsResponse")]
        System.Threading.Tasks.Task<bool> VerifyLocationExistsAsync(ServiceReferenceLocation.Location location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/SearchByName", ReplyAction="http://tempuri.org/ILocation/SearchByNameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLocation.Location> SearchByNameAsync(string locationName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ILocationChannel : ServiceReferenceLocation.ILocation, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class LocationClient : System.ServiceModel.ClientBase<ServiceReferenceLocation.ILocation>, ServiceReferenceLocation.ILocation
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LocationClient() : 
                base(LocationClient.GetDefaultBinding(), LocationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILocation.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocationClient(EndpointConfiguration endpointConfiguration) : 
                base(LocationClient.GetBindingForEndpoint(endpointConfiguration), LocationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LocationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LocationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferenceLocation.Location>> GetLocationsAsync()
        {
            return base.Channel.GetLocationsAsync();
        }
        
        public System.Threading.Tasks.Task AddLocationAsync(ServiceReferenceLocation.Location location)
        {
            return base.Channel.AddLocationAsync(location);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyLocationExistsAsync(ServiceReferenceLocation.Location location)
        {
            return base.Channel.VerifyLocationExistsAsync(location);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLocation.Location> SearchByNameAsync(string locationName)
        {
            return base.Channel.SearchByNameAsync(locationName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILocation))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILocation))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8002/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LocationClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILocation);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LocationClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILocation);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ILocation,
        }
    }
}
