//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosCore.Context
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            this.People = new HashSet<Person>();
        }
        [DataMember]
        public int PhotoId { get; set; }

        [DataMember]
        public System.DateTime DateCreated { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public string Event { get; set; }

        [DataMember]
        public string FilePath { get; set; }

        [DataMember]
        public int LocationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Person> People { get; set; }

        [DataMember]
        public virtual Location Location { get; set; }

        public override string ToString()
        {
            return FilePath;
        }
    }
}
